stages:
  - build
  - upload
  - deploy

build-linux:
  stage: build
  tags:
    - linux
  only:
    - tags
  image: node:fermium-slim
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "target/*.AppImage"
      - "target/*.tar.gz"
      - "target/*.deb"
      - "target/manifests/*.json"
  before_script:
    - apt update
    - apt install -y build-essential python3 pkg-config libsecret-1-0 libsecret-1-dev ca-certificates openssh-client dpkg-dev dpkg-sig
    - yarn
  script:
    - yarn build-production

    - yarn package-linux

build-mac:
  stage: build
  tags:
    - macos
  only:
    - tags
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "target/*.dmg"
      - "target/manifests/*.json"
  before_script:
    - source ~/.zshrc
    - security unlock-keychain -p "$APPLE_CI_HOST_PASSWORD"
    - yarn
  script:
    - yarn build-production

    - yarn package-mac-unsigned

build-windows:
  stage: build
  tags:
    - windows
  only:
    - tags
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "target/*.exe"
      - "target/*.appx"
      - "target/manifests/*.json"
  before_script:
    - yarn
  script:
    - yarn build-production

    - yarn package-windows

upload:
  stage: upload
  only:
    - tags
  image: curlimages/curl:latest
  script:
    - 'cd target && find . -maxdepth 1 -type f | tail --lines=+1 | while read -r line; curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file "${line}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/application/${CI_COMMIT_TAG}/${line}"; done'

deploy:
  stage: deploy
  only:
    - tags
  when: manual
  environment:
    name: production
    url: https://dl.cattr.app
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client gnupg
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - eval $(ssh-agent -s)
    - echo "$CI_SSH_KEY" | base64 -d | ssh-add
    - gpg-agent --daemon
    - echo -e "$DEB_SIGNING_KEY" | base64 -d |  gpg --import
    - RELEASE_VERSION=`(echo $CI_COMMIT_TAG | sed 's/^v//')`
  script:
    - ssh cattr-deploy@dl.cattr.app mkdir -p "/srv/dl/desktop/$RELEASE_VERSION"
    - cd target
    - scp *.dmg "cattr-deploy@dl.cattr.app:/srv/dl/desktop/$RELEASE_VERSION/"
    - scp *.exe "cattr-deploy@dl.cattr.app:/srv/dl/desktop/$RELEASE_VERSION/"
    - scp *.tar.gz "cattr-deploy@dl.cattr.app:/srv/dl/desktop/$RELEASE_VERSION/"
    - scp *.AppImage "cattr-deploy@dl.cattr.app:/srv/dl/desktop/$RELEASE_VERSION/"
    - scp *.deb "cattr-deploy@dl.cattr.app:/srv/dl/packages/deb/amd64/"
    - cd manifests
    - scp * cattr-deploy@dl.cattr.app:/srv/dl/manifests/
  after_script:
    - ssh cattr-deploy@dl.cattr.app "cd /srv/dl/packages/deb && apt-ftparchive --arch amd64 packages amd64 > Packages"
    - ssh cattr-deploy@dl.cattr.app "cd /srv/dl/packages/deb && apt-ftparchive release . > Release"
    - scp "cattr-deploy@dl.cattr.app:/srv/dl/packages/deb/Release" .
    - gpg -abs -o Release.gpg Release
    - gpg --clearsign -o InRelease Release
    - scp Release.gpg "cattr-deploy@dl.cattr.app:/srv/dl/packages/deb/"
    - scp InRelease "cattr-deploy@dl.cattr.app:/srv/dl/packages/deb/"
