plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

nodeLinker: node-modules

npmScopes:
  cattr:
    npmRegistryServer: "https://git.amazingcat.net/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
